#!/usr/bin/env node

const microlinkCards = require('@microlink/cards')
const slugify = require('@sindresorhus/slugify')
const { posts } = require('../posts')

async function main () {
  await microlinkCards({
    mqlOpts: {
      apiKey: process.env.MICROLINK_API_KEY
    },
    entries: posts.map(({ title }) => ({ preset: 'rauchg', title })),
    output: {
      path: './public/cards',
      filename: ({ title }) => slugify(title)
    }
  })
}

main()
  .then(() => process.exit())
  .catch(err => console.error(err) && process.exit(1))
